// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID        string  `json:"id"`
	Text      string  `json:"text"`
	CreatedBy string  `json:"createdBy"`
	Price     float64 `json:"price"`
}

type Mutation struct {
}

type NewMessage struct {
	Text      string `json:"text"`
	CreatedBy string `json:"createdBy"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type Query struct {
}

type Subscription struct {
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
